'use strict';

// Post-vendor patch for syntaxes/viml.tmLanguage.json.
//
// The grammar is generated by `make update-grammar` from upstream
// Alhadis/language-viml. Upstream has no concept of a `:map` command's
// structure: it matches the command word (nnoremap/nmap/...) as a bare
// function keyword and lets the {lhs} and {rhs} fall through to generic
// rules. That produces GitHub issue #74:
//   * the {lhs} (e.g. `qq`, `qs`) gets no scope at all (renders "white");
//   * the {rhs} starting with a register like `"_dd` is swallowed by the
//     inline-comment rule and highlighted as a comment.
//
// This script re-adds a structured map rule, modeled on neovim's
// vimMap -> vimMapLhs -> vimMapRhs chain (runtime/syntax/vim.vim) and
// tree-sitter-vim's map_statement. TextMate has no `nextgroup` state
// machine, so the command word, optional <...> modifiers, and the {lhs}
// are all consumed in the rule's `begin` regex; the region content is then
// exactly the {rhs}, which can never fall through to #comments.
//
// `<expr>` maps are handled by a dedicated earlier branch whose rhs reuses
// the real expression sub-rules (strings/numbers/variables/operators),
// matching how neovim treats `<expr>` right-hand sides.
//
// The script is idempotent: running it on an already-patched grammar is a
// no-op. Run automatically after update-grammar (see Makefile).

const fs = require('fs');
const path = require('path');

const GRAMMAR = path.join(__dirname, '..', 'syntaxes', 'viml.tmLanguage.json');

// Command words: 20 map variants ([nvxsoilct] mode prefix + optional `nore`
// + `map`, plus smap/snoremap). The trailing \b excludes mapclear, unmap,
// mapmode, maparg, etc.
const CMD = '[nvxsoilct]?(?:nore)?map|snoremap|smap';
const MODS = 'buffer|silent|expr|nowait|unique|script';
// Any run of modifiers before the lhs (ordinary branch).
const MOD = `(?:\\s*<(?i:${MODS})>)*`;
// Modifier run that must include <expr> somewhere (expr branch).
const OTHER = 'buffer|silent|nowait|unique|script';
const EXPR_MOD =
  `(?:\\s*<(?i:${OTHER})>)*\\s*<(?i:expr)>(?:\\s*<(?i:${OTHER})>)*`;

function beginCaptures() {
  return {
    1: { name: 'keyword.control.map.viml' },
    2: { name: 'keyword.operator.bang.viml' },
    3: { patterns: [ { include: '#mapModifier' } ] },
    4: {
      name: 'meta.map.lhs.viml',
      patterns: [
        { include: '#mapNotation' },
        { match: '\\S', name: 'entity.name.function.map-lhs.viml' },
      ],
    },
  };
}

function buildRules() {
  // Branch 1: `<expr>` maps - rhs is a VimL expression.
  const mapCommandExpr = {
    name: 'meta.map.expr.viml',
    begin: `(?x) \\b (${CMD}) \\b (!)? (${EXPR_MOD}) \\s+ (\\S+) `,
    beginCaptures: beginCaptures(),
    end: '$',
    contentName: 'meta.map.rhs.expr.viml',
    patterns: [
      { include: '#mapNotation' },
      { include: '#strings' },
      { include: '#numbers' },
      { include: '#variable' },
      { include: '#register' },
      { include: '#keyword' },
      { include: '#expr' },
    ],
  };

  // Branch 2: ordinary maps - rhs is a literal key sequence.
  const mapCommand = {
    name: 'meta.map.viml',
    begin: `(?x) \\b (${CMD}) \\b (!)? (${MOD}) \\s+ (\\S+) `,
    beginCaptures: beginCaptures(),
    end: '$',
    contentName: 'meta.map.rhs.viml',
    patterns: [
      { include: '#mapNotation' },
      { match: '\\S+', name: 'string.unquoted.map-rhs.viml' },
    ],
  };

  const mapModifier = {
    name: 'storage.modifier.map.viml',
    match: `(?i)<(${MODS})>`,
    captures: { 1: { name: 'support.function.vimMapModKey.viml' } },
  };

  // Key notation used in lhs/rhs: <plug>, <cr>, <esc>, <leader>, <c-x>, etc.
  const mapNotation = {
    patterns: [
      {
        name: 'constant.character.notation.viml',
        match:
          '(?i)(<)((?:[csma]-)*(?:plug|sid|nop|silent|cmd|cr|esc|tab|bs|' +
          'space|bar|lt|del|up|down|left|right|home|end|pageup|pagedown|' +
          'f[0-9]{1,2}|(?:local)?leader|k?[0-9]|[a-z]+))(>)',
        captures: {
          1: { name: 'punctuation.definition.bracket.angle.begin.viml' },
          3: { name: 'punctuation.definition.bracket.angle.end.viml' },
        },
      },
    ],
  };

  return { mapCommandExpr, mapCommand, mapModifier, mapNotation };
}

function main() {
  const raw = fs.readFileSync(GRAMMAR, 'utf8');
  const grammar = JSON.parse(raw);
  const repo = grammar.repository;
  if (!repo || !repo.main || !Array.isArray(repo.main.patterns)) {
    throw new Error('Unexpected grammar shape: missing repository.main.patterns');
  }

  const already =
    repo.mapCommand && repo.mapCommandExpr &&
    repo.main.patterns.some(p => p.include === '#mapCommand');
  if (already) {
    console.log('patch-grammar: already patched, nothing to do.');
    return;
  }

  const rules = buildRules();
  repo.mapCommandExpr = rules.mapCommandExpr;
  repo.mapCommand = rules.mapCommand;
  repo.mapModifier = rules.mapModifier;
  repo.mapNotation = rules.mapNotation;

  // Insert both branches at the front of #main so they win over #comments
  // and extraVimFunc. The `<expr>` branch must precede the ordinary one.
  repo.main.patterns.unshift({ include: '#mapCommand' });
  repo.main.patterns.unshift({ include: '#mapCommandExpr' });

  // Match the exact formatting produced by vscode-update-grammar-tool
  // (JSON.stringify with 2-space indent, no trailing newline).
  fs.writeFileSync(GRAMMAR, JSON.stringify(grammar, null, 2));
  console.log('patch-grammar: applied map-command patch for issue #74.');
}

main();
